### PR TITLE
attempt to fix toggle buttons

### PR DESCRIPTION
**Pull request by shinmai**
Quick stab at resolving #10 

Removed some of the JPEG artifacts, quickly redid the circle since it was most artifacted, inverted circle position for on and off and slightly adjusted text position.

Tested very briefly, but looked decent to me.

### CODE REVIEW

**Comment by Sebazzz** [comment]
I'm sorry I didn't review it yet!

Can you please reimplement your change on the extui branch @shinmai? DWIN DGUS is all binary files, so please check the extui branch and do the changes there. Master will not be used going forward, extui is the future.

**Comment by Sebazzz** [comment]
The graphics look fine by the way, except for a loose block of pixels at the off button.

**Comment by shinmai** [comment]
Ah, sorry didn't realise about the branches! I'll PR against extui as soon as I have a spare moment. I'll re-check the off button bitmap while I'm at it.

**Comment by Sebazzz** [comment]
Thanks!

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Aapo Saaristo <notifications@github.com>
Verzonden: Saturday, November 14, 2020 10:37:13 PM
Aan: CR6Community/CR-6-touchscreen <CR-6-touchscreen@noreply.github.com>
CC: Sebastiaan Dammann <sebastiaandammann@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [CR6Community/CR-6-touchscreen] attempt to fix toggle buttons (#13)


Ah, sorry didn't realise about the branches! I'll PR against extui as soon as I have a spare moment. I'll re-check the off button bitmap while I'm at it.

**Comment by Sebazzz** [comment]
Please change the bitmaps, but keep the ICL files as-is because @grobux is doing a re-design.

**Comment by Sebazzz** [comment]
Please re-open pull request on extui when ready 👍

**Pull request closed without merging**
