### PR TITLE
Update README.md with extra instructions for the SD-card format needed

### PR DESCRIPTION
**Pull request by dingo35**
Just adding some small remarks that cost me a few hours to find out... Hope to save other people some time!

### CODE REVIEW

**Comment by Sebazzz** [comment]
Thank you @dingo35 

Would it be useful to add an example command line command too?

**Comment by dingo35** [comment]
Sure, the instructions would be:
[code]
fdisk /dev/sdX where sdX is your SD card's device
In fdisk:
o (new dos partition table)
n (new partition)
p (primary)
1 (partition nr)
8192 (starting sector)
enter (last sector)   ---> if your SD card is bigger than 8Gb, enter a lower sector number here so that the partition <8Gb
t (change type)
b (hex code of W95 FAT32)
w (write all changes to sd-card)

From the command line:
mkfs.fat -F 32 -s 8 /dev/sdX1
fsck.fat -v /dev/sdX1
mount /dev/sdX1 /mnt

For mainboard firmware:
cp /path/to/mainboard_firmware.bin /mnt
For touchscreen firmware:
cp -r /path/to/touchscreen-firmware/DWIN_SET /mnt
[/code]

**Comment by Sebazzz** [comment]
Okay, could you add that to your PR?

Code blocks are btw indented (four spaces)  or delimited by two newlines with \```

**Comment by dingo35** [comment]
Done.

**Comment by Sebazzz** [comment]
Thank you @dingo35 - merged!

**Pull request merged**
