### PR TITLE
Updated Home, Setup and PID screens - added new Calibrate screen

### PR DESCRIPTION
**Pull request by ztakis**

### CODE REVIEW

**Comment by Sebazzz** [comment]
Did you add the M117 to the setup screen intentionally?

**Comment by Sebazzz** [comment]
Awesome!

**Comment by ztakis** [comment]
> 
> 
> Did you add the M117 to the setup screen intentionally?

No, I was careless. Do you want me to correct it now?

**Comment by Sebazzz** [comment]
Yup, it has no use there now :)

**Pull request merged**
